# Basic Site Settings
locale                   : "en-GB"
site_theme               : "default"
title                    : "Hamidreza Alavi"
title_separator          : "-"
name                     : &name "Hamidreza Alavi"
description              : &description "Senior Lecturer in Construction Informatics at Oxford Brookes University; Academic Affiliate at the University of Cambridge."
url                      : "https://hr-alavi.github.io"
baseurl                  : ""
repository               : "Hr-Alavi/Hr-Alavi.github.io"

# Site Author (sidebar)
author:
  # Biographic information
  avatar           : "profile.png"   # put your photo at /images/profile.png
  name             : "Hamidreza Alavi"
  pronouns         :
  bio              : "Senior Lecturer in Construction Informatics at Oxford Brookes University; Academic Affiliate at the University of Cambridge. Research interests: Digital Twins, BIM, AI/ML for the built environment, facility/asset management, and construction automation."
  location         : "Oxford, United Kingdom"
  employer         : "Oxford Brookes University"
  uri              :
  email            : "h.alavi@brookes.ac.uk"

  # Academic websites
  academia         :
  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=Pgm3uLIAAAAJ&hl=en"
  inspire-hep      :
  impactstory      :
  orcid            :
  semantic         :
  ssrn             :
  pubmed           :
  researchgate     :
  scopus           :
  zotero           :

  # Repositories and software development
  bitbucket        :
  codepen          :
  dribbble         :
  github           : "Hr-Alavi"
  kaggle           :
  stackoverflow    :

  # Social media
  artstation       :
  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
